// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserSegmentationService.Infrastructure.Persistence.Database;

#nullable disable

namespace UserSegmentationService.Infrastructure.Migrations
{
    [DbContext(typeof(SegmentationDbContext))]
    partial class SegmentationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserSegmentationService.Domain.Entities.UserMetric", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SpendLast60Days")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("UserMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
